version: '3.0'
#networks:
#  my_network:
#    driver: bridge
services:
  mysql:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "db_example"
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      #      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database:/var/lib/mysql
  redis-spring-boot:
    image: redis:alpine
    ports:
      - 6380:6379
    tty: true
#    networks:
#      - my_network
#  account-service:
#    depends_on:
#      - mysql
#    container_name: account-service
#    image: cuongpham11121998/account-service:v1.0.0
#    ports:
#      - "8888:8088"
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456789
#      MYSQL_PORT: mysql
#      MYSQL_DATABASE: db_example
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 123456789
#    stdin_open: true
#    tty: true
#    networks:
#      - my_network
#    links:
#      - mysql
volumes:
  mysql:
    driver: local

