spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3308}/${MYSQL_DATABASE:db_example}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456789}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "85998077224-t35s1f5h11lvf1nkdbm448dselumfs5t.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "http://localhost:8088/login-google"
          scope:
            - email
            - profile
            - name
  service:
    product-service:
      url: http://localhost:8089/v1/products
      basic-auth: Basic dXNlcjpwYXNzd29yZA==

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 123456789

google:
  app:
    id: 85998077224-t35s1f5h11lvf1nkdbm448dselumfs5t.apps.googleusercontent.com
    secret: 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
  redirect:
    uri: http://localhost:8088/login-google
  link:
    get:
      token: https://accounts.google.com/o/oauth2/token
      user_info: https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token=
server:
  port: 8088
